### ISSUE TITLE
Define State-of-Charge Message

### ISSUE THREAD

**Issue by mikeferguson** [fetchrobotics/power_msgs#3]
This issue is to track thoughts on a state-of-charge message. A few references:

 * [pr2_msgs/PowerState](http://docs.ros.org/api/pr2_msgs/html/msg/PowerState.html)
 * [kobuki_msgs/PowerSystemEvent](http://docs.ros.org/indigo/api/kobuki_msgs/html/msg/PowerSystemEvent.html)

@dbking77 feel free to add thoughts from the state-of-charge estimation side. @ablasdel please add any thoughts regarding how you might display this in a dashboard.

**Comment by awesomebytes** [comment]
Hello, I was talking with @ablasdel recently about making a simple and standard message (mainly to go with [this GUI for showing the battery status]( https://github.com/pal-robotics/rqt_batteries) based on rqt_dashboard but trying to minimize setup for it to work in the sense of not needing to write code to have it working).

I propose something looking like:

    # Current % of battery
    Float32 percentage

    # Charging status
    Bool charging

To keep it very simple.

**Comment by awesomebytes** [comment]
Made a PR of the message: https://github.com/fetchrobotics/power_msgs/pull/4 

And modified my plugin to support it: 
https://github.com/awesomebytes/rqt_batteries/tree/support_default_battery_status

You can try it if you are curious checking it out and all that stuff and executing:

    rosrun rqt_batteries test_plugin.py

    rosrun rqt_batteries rqt_batteries

**Comment by dbking77** [comment]
It might make more sense to have a "details" string in the battery status message and use that as the tooltip in the GUI.   I think this would provide more flexibility for different systems to provide customized details about the battery state.    If the details string was blank, the GUI could generate a generic tooltip that displayed the capacity.

For our system, I would like to provide and estimated runtime, or estimate charge time when charging.  However, this might make sense for all systems.

**Comment by awesomebytes** [comment]
I was gonna generate that tooltip based on a `time` field. If the robot has the field charging as true, the time should reflect how long to charge. If the robot has charging as false, the time should reflect the time left for the battery.
Sounds good?

**Comment by dbking77** [comment]
If you are going to take that route, then I would suggest adding the battery name to message.   Then no configuration is needed to properly use the widget.

**Comment by awesomebytes** [comment]
The name is mainly for when there is more than one battery and I don't
expect to support multiple batteries with this simple topic interface.

In the tooltip I was gonna show the percentage, but if this info is
available I'll show percentage and time.

**Comment by mikeferguson** [comment]
As with breakers, there may be multiple in a system, and so as with the BreakerState we should include a name.

Also, it looks like the CMake did not get updated for the filename change.

**Comment by awesomebytes** [comment]
Hmm I'm on my phone right now, I left the commits half way before leaving.
I think we are losing focus on having a simple message.

**Comment by ablasdel** [comment]
I agree that having a simple message is nice, but there is also something to be said for functionality.

If we add some extra useful non-mandatory fields that are often useful as suggested above I don't think it will be a problem.

**Comment by awesomebytes** [comment]
Ok, I've been thinking a bit about it. I agree on the name field, but I would like to ask you if you can direct me to some example rqt_gui ptython code to open a little config window pressing the "configure" button to show the dropdown list of topics of type BatteryState to choose in every tiny plugin what battery topic you wanna listen (as I want the widget to be tiny, and adding the dropdown directly would lose that feature).
I've taken a look into rqt_console but... there is a lot of stuff going on that got me confused. Do you know any other piece of code that could help me?

P.S.: I'll be on holidays for a week, I'll work on it after them.

**Comment by ablasdel** [comment]
Off the top of my head quickly here are some pointers.

In python you can use rosmsg package to list the messages like this:
```
rosmsg.list_msgs(*packagename*)
```
then get the message class and compare it to BatteryState
```
roslib.message.get_message_class(*msg name*)
```

This will give you the data for your list.

While it doesn't give you exactly what you want "rqt_logger_level" is much smaller and will give a good primer on how to open up a window with a list box in it.

There might be a simpler way to bring up a Qt list selector but I don't recall it.

Have fun on your trip!

**Comment by ablasdel** [comment]
#5 looks like a really good answer to this issue. @awesomebytes lets's chat when you get back.
