### ISSUE TITLE
relation to standart ROS msg

### ISSUE THREAD

**Issue by ensonic** [fetchrobotics/power_msgs#7]
There is also:
http://docs.ros.org/api/sensor_msgs/html/msg/BatteryState.html
can this be used instead? Also are these message currnenty posted and if so on which topic? It would be awesome to expand the README a bit.

**Comment by mikeferguson** [comment]
The sensor_msgs::BatteryState message were released about 6 months after we released this package.

Most of our ROS API is documented on http://docs.fetchrobotics.com/api_overview.html, but it looks like this is missing. I've created a ticket for that over [here](https://github.com/fetchrobotics/docs/issues/52), but in the meantime, I believe this message is published on the topic "battery_state" -- but you can also get a full list of topics coming out of the drivers with "rosnode info robot_driver".
